services:
  app:
    entrypoint:
    - sleep
    - infinity
    build:
      context: .
      dockerfile: docker/dev/dockerfile
    ports:
     - "3300:3200"
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock