services:
  development:
    entrypoint:
    - sleep
    - infinity
    build:
      context: .
      dockerfile: docker/dev/dockerfile
    environment:
      - HOST_WORKING_DIR=${PWD}
    ports:
     - "3200:3200"
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock