// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTxDDhthb89UFg1VyPrmWNqUp8dVtDFdc',
    appId: '1:177243638780:web:f14f427786506a6df5c079',
    messagingSenderId: '177243638780',
    projectId: 'eunityusa',
    authDomain: 'eunityusa.firebaseapp.com',
    storageBucket: 'eunityusa.firebasestorage.app',
    measurementId: 'G-FFXL1G3NMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs9Mq2uwt81GPJexLMv8olQrvaJjqTo-M',
    appId: '1:177243638780:android:12f0fbca606c23b5f5c079',
    messagingSenderId: '177243638780',
    projectId: 'eunityusa',
    storageBucket: 'eunityusa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABAo-6lyS9sX8HRN8sWdFueoNWEG2C5sE',
    appId: '1:177243638780:ios:4f1dabff1cef05b2f5c079',
    messagingSenderId: '177243638780',
    projectId: 'eunityusa',
    storageBucket: 'eunityusa.firebasestorage.app',
    iosClientId: '177243638780-ae7ru5mf65e9uurcnhob51rfi4rddckg.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABAo-6lyS9sX8HRN8sWdFueoNWEG2C5sE',
    appId: '1:177243638780:ios:4f1dabff1cef05b2f5c079',
    messagingSenderId: '177243638780',
    projectId: 'eunityusa',
    storageBucket: 'eunityusa.firebasestorage.app',
    iosClientId: '177243638780-ae7ru5mf65e9uurcnhob51rfi4rddckg.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTxDDhthb89UFg1VyPrmWNqUp8dVtDFdc',
    appId: '1:177243638780:web:6f7b7684ff57e429f5c079',
    messagingSenderId: '177243638780',
    projectId: 'eunityusa',
    authDomain: 'eunityusa.firebaseapp.com',
    storageBucket: 'eunityusa.firebasestorage.app',
    measurementId: 'G-VEZ97WJSYK',
  );
}
