

# Use golang:1.23-alpine as the base image
FROM golang:1.23-rc-alpine

WORKDIR /app

# Install necessary tools for debugging
RUN apk add --no-cache bash curl

# Copy application files into the container
COPY ../../. .

RUN apk add --no-cache \
    pkgconfig \
    vips-dev \
    g++ \
    make

RUN go mod tidy
RUN go build -o main .
RUN chmod +x main


EXPOSE 3200

# # Set the entrypoint to bash for debugging
# ENTRYPOINT ["bash"]
# CMD can be specified here if you want a default command
CMD ["make","serve"]
