

# Use golang:1.23-alpine as the base image
FROM golang:1.23-rc-alpine AS builder

RUN apk add --no-cache \
    pkgconfig \
    vips-dev \
    g++ 

RUN apk add --no-cache bash curl

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download


COPY . .

# Build the Go app
RUN go build -o main .


# Stage 2: Run the Go binary
FROM alpine:latest

# Install required libraries
RUN apk add --no-cache \
    libgcc \
    pkgconfig \
    vips-dev \
    g++

# Set the Current Working Directory inside the container
WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/main .
COPY --from=builder /app/.env .


# Expose port 8080 to the outside world
EXPOSE 3200

# Command to run the executable
CMD ["./main"]
